### ISSUE TITLE
Revamp whole site

### ISSUE THREAD

**Issue by ashishagarwal2023** [thetrouper/ClickCrystalsXYZ#19]
When? @TutlaMC @ItziSpyder @thetrouper 

Its funny to see how dead this repo, and even the ClickCrystals one is, after me leaving, ClickCrystals might be dead for no interest , yea cool

I just remmember how yall kicked me + telling you that I've quit all games so don't ask me back. Plus I mailed you regarding your grammar mistakes and you didn't even reply (either it is your skill issue to not check it, or you literally are scared fr)
![image](https://github.com/thetrouper/ClickCrystalsXYZ/assets/83082760/c6e0307f-e122-4a28-aee6-6dd14b71a1b9)
bro got to only blaim it on wither123go

**Comment by thetrouper** [comment]
Bruh ImproperIssues can't just only do ClickCrystals. They are currently working on other stuff such as a hacked client and learning OpenGL. I don't see why you need to be so toxic about slow progress on the client, everyone needs a break to do something else at some point. You don't have to act like you're the stuff.

**Comment by ashishagarwal2023** [comment]
Bruh how many languages he speak? Don't include the programming languages and I bet he speak only 1 language after english.

I'm a indian and self-learned english, am youung you can check my profile, and I am not meaning "toxic" I just want to see how the project that thought me useless literally broke, fr.

and now bro is fr going to cheat, hopefully his client will go such in sky that he will also go with his client.

**Comment by TutlaMC** [comment]
@ashishag
arwal2023, ClickCrystals has paused development as many of the staff members are engrossed in other fields; including me as I have an exam. We are currently developing a hacked client & not ClickCrystals, the development of ClickCrystal's website will begin in April. 

Even I'm Indian but I know English fluently & speak Hindi too. I'm even learning Arabic & southern Indian languages. My mother tongue is completely different from the province I live in and I have learnt the language of the province. Don't attack our staff members for their language.

ClickCrystals didn't die as you left, you got demoted cause you didn't do what we said so there is no logic behind in saying it died because of you leaving.

**Let me address:**

> _"I'm a indian and self-learned english, am youung you can check my profile, and I am not meaning "toxic" I just want to see how the project that thought me useless literally broke, fr."_

Your claiming you aren't toxic? Then please read your description to this issue and we will clarify accordingly.

**Comment by ashishagarwal2023** [comment]
bro nvm let  me block this guy

**Comment by I-No-oNe** [comment]
> bro nvm let me block this guy

:skull:

**Comment by ashishagarwal2023** [comment]
bro just look yall were such toxic that yall banned me from server even i worked for yall's website
and look: yall didnt fixed the spelling i mailed @ItziSpyder in the site even after 3 months and yall are literally still dependent on my site i made L fr

**Comment by ashishagarwal2023** [comment]
> @ashishag arwal2023, ClickCrystals has paused development as many of the staff members are engrossed in other fields; including me as I have an exam. We are currently developing a hacked client & not ClickCrystals, the development of ClickCrystal's website will begin in April.
> 
> Even I'm Indian but I know English fluently & speak Hindi too. I'm even learning Arabic & southern Indian languages. My mother tongue is completely different from the province I live in and I have learnt the language of the province. Don't attack our staff members for their language.
> 
> ClickCrystals didn't die as you left, you got demoted cause you didn't do what we said so there is no logic behind in saying it died because of you leaving.
> 
> **Let me address:**
> 
> > _"I'm a indian and self-learned english, am youung you can check my profile, and I am not meaning "toxic" I just want to see how the project that thought me useless literally broke, fr."_
> 
> Your claiming you aren't toxic? Then please read your description to this issue and we will clarify accordingly.

bro learn how to spell my name first

**Comment by TutlaMC** [comment]
> bro just look yall were such toxic that yall banned me from server even i worked for yall's website and look: yall didnt fixed the spelling i mailed @ItziSpyder in the site even after 3 months and yall are literally still dependent on my site i made L fr

You do know your fix wasn't actually a fix. Noting here means "knowing", it's not a typo for "nothing" that would mean the complete opposite.

This indicates you didn't actually put effort and just wanted to do a PR despite completetly changing what was meant, you didn't even look in what you changed meant

**Comment by TutlaMC** [comment]
> > bro learn how to spell my name first
> 
> The reason I made spelling errors was because of a simple fact: typing for long hours could wear out the fingers. Before I made the wiki, I had to type out multiple digital assignment responses. It's from some place called school, in which you have probably never been to one. To add salt to injury, I also had to type out wikis for ClickCrystals, most of which were drafts. @thetrouper is a witness to me tryharding multiple documents before I finally came up with the Google document version. And above all that, typos are a seemingly common mistake amongst all keyboard users; typing usually comes with making a mistake of an edit distance up to 2-4. Edit distances within this area tend to be corrected by Google Document's autocorrect, sometimes having the defect of swapping in a word with 0 relevance to the context.
> 
> As for not seeing your email, you must know as a high school student who is considered academically responsible I have tons of emails to check everyday, whether or not it is an assignment creation, submission return, or even club meetings.
> 
> To top it all off, the word "interpreted" was misinterpreted by Gdoc and corrected to "interrupted". And for the error in "scripts and macros", I simply just left out the word "create" at the beginning because my mind thinks faster than I type, resulting me in believing I have already typed the word before I continued to type the rest of the sentence.

He wasn't talking about the GoogleDoc and we have all seen his PR 💀

**Comment by ItziSpyder** [comment]
> > > bro learn how to spell my name first
> > 
> > 
> > The reason I made spelling errors was because of a simple fact: typing for long hours could wear out the fingers. Before I made the wiki, I had to type out multiple digital assignment responses. It's from some place called school, in which you have probably never been to one. To add salt to injury, I also had to type out wikis for ClickCrystals, most of which were drafts. @thetrouper is a witness to me tryharding multiple documents before I finally came up with the Google document version. And above all that, typos are a seemingly common mistake amongst all keyboard users; typing usually comes with making a mistake of an edit distance up to 2-4. Edit distances within this area tend to be corrected by Google Document's autocorrect, sometimes having the defect of swapping in a word with 0 relevance to the context.
> > As for not seeing your email, you must know as a high school student who is considered academically responsible I have tons of emails to check everyday, whether or not it is an assignment creation, submission return, or even club meetings.
> > To top it all off, the word "interpreted" was misinterpreted by Gdoc and corrected to "interrupted". And for the error in "scripts and macros", I simply just left out the word "create" at the beginning because my mind thinks faster than I type, resulting me in believing I have already typed the word before I continued to type the rest of the sentence.
> 
> He wasn't talking about the GoogleDoc and we have all seen his PR 💀

he was, it's in the email I didn't get to read

**Comment by ItziSpyder** [comment]
> bro nvm let me block this guy

Blocking someone for point out the facts, not to mention without the use of profanity, is an immature act.

**Comment by TutlaMC** [comment]
> > bro nvm let me block this guy
> 
> Blocking someone for pointing out the facts, not to mention without the use of profanity, is an immature act.

![image](https://github.com/thetrouper/ClickCrystalsXYZ/assets/91965613/e5fdd775-5faa-47c4-8cbe-624cffc74d16)
![image](https://github.com/thetrouper/ClickCrystalsXYZ/assets/91965613/986690d8-f374-4a2a-ba31-95f8c197592d)
![image](https://github.com/thetrouper/ClickCrystalsXYZ/assets/91965613/735ca618-8ce1-47c9-a5e1-6579fb0d6b88)
Bro got killed

**Comment by ItziSpyder** [comment]
And @ashishagarwal2023 ClickCrystals repository was already not receiving weekly pushes when you were in the server. What made you think that it would be normal to expect any motion just because you left? Do note your departure has not and will never affect the community. 

As for "the site you made", remember how the site was asked to be revamped but you did nothing. At this very moment 90% of the site is still done by me; your contributions are nothing but a tiny fraction of The ClickCrystals Project. Our staff team will not acquiesce to irresponsibility and incompetence.

**Comment by TutlaMC** [comment]
> And @ashishagarwal2023 ClickCrystals repository was already not receiving weekly pushes when you were in the server. What made you think that it would be normal to expect any motion just because you left? Do note your departure has not and will never affect the community.
> 
> As for "the site you made", remember how the site was asked to be revamped but you did nothing. At this very moment 90% of the site is still done by me; your contributions are nothing but a tiny fraction of The ClickCrystals Project. Our staff team will not acquiesce to irresponsibility and incompetence.

![image](https://github.com/thetrouper/ClickCrystalsXYZ/assets/91965613/f57bdd6c-9734-4e0a-9def-f4725a8d5e7c)
You mean 40%

**Comment by ItziSpyder** [comment]
> You mean 40% (I'm not defending him)

No, all he did was add .MD files with content pasted over from https://bit.ly/ccs-wiki. Those belong to me.

**Comment by TutlaMC** [comment]
@ashishagarwal2023 Summary:
- You blocking us did not help as your just trying to get away and prevent unban.
- Your efforts was mainly just MD files
- Your PR showed how much you actually cared, "noting" meant "knowing" here not a typo for "nothing" (Another grammatical error)
- Improper was really busy and autocorrect messed up the grammar in the Google Doc don't blame him
- Wither123go was who you ere fighting with not Improper
- 80% of the Website was done by the community and the project isn't dead as:
 - Most of the staff are working on other things
 - Coherent is in development
 - This is exam time for most East Asians
 - We are still receiving contributions and you can't see them
- Your being toxic and calling us toxic for banning you after you left
- Your cringe

**Comment by ashishagarwal2023** [comment]
bro go whats your issue 
stop pinging me

**Comment by ashishagarwal2023** [comment]
not were there 8 contributors and 80%

**Comment by TutlaMC** [comment]
> not were there 8 contributors and 80%

Go back to fifth and learn percentage 🙏

**Comment by ashishagarwal2023** [comment]
![image](https://github.com/thetrouper/ClickCrystalsXYZ/assets/83082760/0c79d03a-426a-4026-b061-94ccc6989636)
yeah noticing 1month elpased and bro didnt learned how to fix a simple foooter without using chatgpt :skull:

**Comment by TutlaMC** [comment]
> ![image](https://private-user-images.githubusercontent.com/83082760/315544045-0c79d03a-426a-4026-b061-94ccc6989636.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwMzkxNTIsIm5iZiI6MTcxMTAzODg1MiwicGF0aCI6Ii84MzA4Mjc2MC8zMTU1NDQwNDUtMGM3OWQwM2EtNDI2YS00MDI2LWIwNjEtOTRjY2M2OTg5NjM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDE2MzQxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYWM0MmVjM2I2MGExZGI5NDUwNWVlYTNjN2MxOGYwZTBkYTAwZmI2MjAwY2I2MDAwZDZjZTAwNmVlYWZmNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Nel2jvedAfapLbmFHsZkWG3u1lmX3LWgjuuPCe0CylE) yeah noticing 1month elpased and bro didnt learned how to fix a simple foooter without using chatgpt 💀

Like I said before: we haven't started the website yet you keep saying the same thing like a 79 year old grandma.

**Comment by ashishagarwal2023** [comment]
dude fighting a toxic bud is more like telling a snake how to not kill

**Comment by ashishagarwal2023** [comment]
bros quiet now because his mates are sleeping fr and when a kid is alone

**Comment by TutlaMC** [comment]
> dude fighting a toxic bud is more like telling a snake how to not kill

Rephrase your setence, that makes no sense. Again, your blocking people without profanity and apparently that isn't "toxic". Please do note the term "toxic" is even understood by middle schoolers

**Comment by ItziSpyder** [comment]
> bros quiet now because his mates are sleeping fr and when a kid is alone

Bro thinks anyone who doesn't reply is sleeping. Unbeknownst to you, like I said before, there is something called school. In which you have probably never been to one.

**Comment by thetrouper** [comment]
Can yall stop commenting on a public discord repository, and perhaps move to discord. I do not want to flood people's email with flame war notifications.

**Comment by ItziSpyder** [comment]
> Can yall stop commenting on a public discord repository, and perhaps move to discord. I do not want to flood people's email with flame war notifications.

Click the unsub button to your right.

**Comment by TutlaMC** [comment]
> Can yall stop commenting on a public discord repository, and perhaps move to discord. I do not want to flood people's email with flame war notifications.

He blocked us
